version: 2
updates:
    - package-ecosystem: nuget
      directory: /
      schedule:
          interval: daily
          time: "00:00"
          timezone: America/Detroit
      ignore:
          # This dependency must not be bumped as doing so will cause issues in downstream projects.
        - dependency-name: Microsoft.Windows.CSWinRT
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: daily
          time: "00:00"
          timezone: America/Detroit
