<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-x86;win-arm64</RuntimeIdentifiers>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <Platforms>x64;x86;ARM64</Platforms>

    <PackageId>Sunburst.MRTCore</PackageId>
    <Authors>William Kent</Authors>
    <Company>William Kent</Company>
    <Title>Standalone MRT Core</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/wjk/MRTCore</PackageProjectUrl>

    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <NoWarn>NU5100</NoWarn>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <NativeProjectReference Include="..\Microsoft.ApplicationModel.Resources.Native\Microsoft.ApplicationModel.Resources.vcxproj" CsWinRTSource="true" />
    <NativeProjectReference Include="..\MRM\MRM.vcxproj" />
  </ItemGroup>

  <PropertyGroup>
    <CSWinRTIncludes>Microsoft.ApplicationModel.Resources</CSWinRTIncludes>
  </PropertyGroup>

  <ItemGroup>
    <CsWinRTInputs Include="$(OutDir)/**/*.winmd" />
  </ItemGroup>	

  <ItemGroup>
    <None Include="Directory.Build.targets" />
    
    <Content Include="priconfig.xml">
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
    <Content Include="Sunburst.MRTCore.props">
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
    <Content Include="Sunburst.MRTCore.targets">
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
  </ItemGroup>

</Project>
