<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Microsoft.ApplicationModel.Resources</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PackageId>Sunburst.MRTCore</PackageId>
    <Authors>William Kent</Authors>
    <Company>William Kent</Company>
    <Title>Standalone MRT Core</Title>
    <Copyright>Copyright © 2026 William Kent. All rights reserved.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/wjk/MRTCore</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- This must all be on one line because the NuGet packing process doesn't strip whitespace properly. -->
    <PackageDescription>This repository contains a copy of MRT Core, packaged so it can be used separately from WinUI 3. It also includes a set of MSBuild targets that create a self-contained PRI file from the contents of a given folder, for use with MRT Core.</PackageDescription>

    <AssemblyTitle>$(Title)</AssemblyTitle>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <NoWarn>NU5100</NoWarn>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="all" />
    <NativeProjectReference Include="..\MRM\MRM.vcxproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Directory.Build.targets" />

    <Content Include="..\..\README.md">
      <Pack>true</Pack>
      <PackagePath></PackagePath>
      <Link>README.md</Link>
    </Content>

    <Content Include="priconfig.xml">
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
    <Content Include="Sunburst.MRTCore.props">
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
    <Content Include="Sunburst.MRTCore.targets">
      <Pack>true</Pack>
      <PackagePath>build</PackagePath>
    </Content>
  </ItemGroup>

</Project>
