<Project>
  <PropertyGroup>
    <AssemblyCompany>William Kent</AssemblyCompany>
    <AssemblyProduct>Standalone MRT Core</AssemblyProduct>
    <AssemblyCopyright>Copyright © 2026 William Kent. All rights reserved.</AssemblyCopyright>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ProjectCapability Include="PackageReferences" />
  </ItemGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ResolveNuGetPackages>false</ResolveNuGetPackages>
    <TargetFrameworkMoniker>native,Version=0.0</TargetFrameworkMoniker>
    <NuGetTargetMoniker>native,Version=0.0</NuGetTargetMoniker>
  </PropertyGroup>

  <Import Project="$(MSBuildProjectExtensionsPath)$(MSBuildProjectFile).*.props"
          Condition="'$(MSBuildProjectExtension)' == '.vcxproj' and Exists('$(MSBuildProjectExtensionsPath)$(MSBuildProjectFile).*.props')" />
</Project>
