<Project>
  <Import Project="..\RepoRoot.props" />
  <Import Project="$(RepoRootPath)build\Directory.Build$(MSBuildProjectExtension).props"/>

  <PropertyGroup>
    <AssemblyCompany>William Kent</AssemblyCompany>
    <AssemblyProduct>Standalone MRT Core</AssemblyProduct>
    <AssemblyCopyright>Copyright © 2026 William Kent. All rights reserved.</AssemblyCopyright>
  </PropertyGroup>
</Project>
