name: Test PR Build

on:
  pull_request:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/pr-tester.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v7
      name: Clone
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v6
      name: Install .NET Core
      with:
        dotnet-version: 10.0.400

    - uses: microsoft/setup-msbuild@v3.0.0
      name: Configure Visual Studio

    - name: Restore
      working-directory: ./src
      run: |
        & MSBuild.exe /t:Restore

    - name: Build
      working-directory: ./src/Sunburst.MRTCore
      run: |
        & MSBuild.exe /nologo /m /p:Configuration=Release /t:Pack

    - uses: actions/upload-artifact@v7
      name: Upload Assets
      with:
        name: nuget
        path: bin/Packages/Release/*.nupkg
        if-no-files-found: error
