name: Test PR Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
      name: Clone
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v6
      name: Install .NET Core
      with:
        dotnet-version: 5.0.100
    - uses: microsoft/setup-msbuild@v3.0.0
      name: Configure Visual Studio
    - name: Build
      working-directory: ./src/Sunburst.MRTCore
      run: |
        & MSBuild.exe /nologo /restore /m /p:Configuration=Release /t:Pack
    - uses: actions/upload-artifact@v7
      name: Upload Assets
      with:
        name: nuget
        path: bin/Packages/Release/*.nupkg
        if-no-files-found: error
